### ISSUE TITLE
Fail to register 

### ISSUE THREAD

**Issue by curiousgg** [janten/dpt-rp1-py#107]
Hi, I followed the instructions regarding downloading/installing the code via pip3.
This seems to have worked.
Yet registering the device is not working as of now. Let me state that I am running ubuntu 18.04.1 LTS 
and if I connect the device via usb it isn't recognized. If I try to connect via bluetooth ... then I can see the device on my machine but when i connect it/ubuntu is giving me a password to plug into the device. The device though has no response to the password request ... there is nothing that i can plug into the device and thus the connection ceases ....
wifi doesn't seem to work at all. 

I tried several times the suggestions outlined above. 

`Cleaning up...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f6830e06a58>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.0.0.1', port=8080): Max retries exceeded with url: /register/cleanup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6830e06a58>: Failed to establish a new connection: [Errno 110] Connection timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/dptrp1/cli/dptrp1.py", line 206, in main
    do_register(dp, args.key or default_privatekey, args.client_id or default_deviceid)
  File "/usr/local/lib/python3.6/dist-packages/dptrp1/cli/dptrp1.py", line 139, in do_register
    _, key, device_id = d.register()
  File "/usr/local/lib/python3.6/dist-packages/dptrp1/dptrp1.py", line 154, in register
    r = self.session.put(register_cleanup_url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 578, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.1', port=8080): Max retries exceeded with url: /register/cleanup (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6830e06a58>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`

**Comment by janten** [comment]
Could you double check whether 10.0.0.1 really is the address of your reader?
