### ISSUE TITLE
Attempting to register - AttributeError: 'list' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by drbryce** [janten/dpt-rp1-py#122]
xubuntu 21.04
python 3.9

I'm attempting to register my usb connected device from the command line with `dptrp1 register` and getting the following python error:
```
bryce@xubuntu:~$ dptrp1 register
Discovering Digital Paper for 30 seconds…
Traceback (most recent call last):
  File "/home/bryce/.local/bin/dptrp1", line 8, in <module>
    sys.exit(main())
  File "/home/bryce/.local/lib/python3.9/site-packages/dptrp1/cli/dptrp1.py", line 339, in main
    dp = DigitalPaper(
  File "/home/bryce/.local/lib/python3.9/site-packages/dptrp1/dptrp1.py", line 158, in __init__
    self.addr = lookup.find(id)
  File "/home/bryce/.local/lib/python3.9/site-packages/dptrp1/dptrp1.py", line 126, in find
    ServiceBrowser(zc, ["_digitalpaper._tcp.local.", "_dp_fujitsu._tcp.local."], self)
  File "/usr/lib/python3/dist-packages/zeroconf/__init__.py", line 1393, in __init__
    if not type_.endswith(service_type_name(type_, allow_underscores=True)):
AttributeError: 'list' object has no attribute 'endswith'
```

Let me know if there's any more info I can provide.

**Comment by drbryce** [comment]
To add on to this, trying to register using an IP address gives different python errors.
```
bryce@xubuntu:~$ dptrp1 register --addr 192.168.1.93
Cleaning up...
<Response [204]>
Requesting PIN...
Encoding nonce...
Traceback (most recent call last):
  File "/home/bryce/.local/bin/dptrp1", line 8, in <module>
    sys.exit(main())
  File "/home/bryce/.local/lib/python3.9/site-packages/dptrp1/cli/dptrp1.py", line 345, in main
    do_register(
  File "/home/bryce/.local/lib/python3.9/site-packages/dptrp1/cli/dptrp1.py", line 208, in do_register
    _, key, device_id = d.register()
  File "/home/bryce/.local/lib/python3.9/site-packages/dptrp1/dptrp1.py", line 239, in register
    if base64.b64decode(m3["a"]) != n2:
KeyError: 'a'
```

**Comment by janten** [comment]
Support for multiple service types has only been added to python-zeroconf [a year ago](https://github.com/jstasiak/python-zeroconf/commit/a6ad100a60e8434cef6b411208eef98f68d594d3). You should probably update it using `pip3 install -U zeroconf`. The dependencies of dpt-rp1-py have been updated accordingly.
