### ISSUE TITLE
registering no longer works

### ISSUE THREAD

**Issue by Altitude-Dashboard** [janten/dpt-rp1-py#123]
This used to work but now registering fails with:

dptrp1 register
Discovering Digital Paper for 30 seconds…
Found Digital Paper with serial number 4118104
To discover only this specific device, call:

    /Users/codrut/Library/Python/3.8/bin/dptrp1 --serial 4118104 register

Found digital paper at 192.168.1.59
To skip the discovery process (and this message), call:

    /Users/codrut/Library/Python/3.8/bin/dptrp1 --addr 192.168.1.59 register

Cleaning up...
<Response [204]>
Requesting PIN...
Encoding nonce...
Traceback (most recent call last):
  File "/Users/codrut/Library/Python/3.8/bin/dptrp1", line 10, in <module>
    sys.exit(main())
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/cli/dptrp1.py", line 345, in main
    do_register(
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/cli/dptrp1.py", line 208, in do_register
    _, key, device_id = d.register()
  File "/Users/codrut/Library/Python/3.8/lib/python/site-packages/dptrp1/dptrp1.py", line 239, in register
    if base64.b64decode(m3["a"]) != n2:
KeyError: 'a'

Quaderno, macOS 11.4 M1, Python 3.8 (built-in)

**Comment by Altitude-Dashboard** [comment]
TBH, it works now, all I did was uninstall the Digital Paper App.
