### ISSUE TITLE
Random error during register process (Quaderno A4 v2)

### ISSUE THREAD

**Issue by vico** [janten/dpt-rp1-py#134]
During updating the configuration location logic, I randomly encountered the following error. 

`(venv) cuong@deepserver:~/localdev/dpt-rp1-py$ dptrp1 register
Discovering Digital Paper for 30 seconds…
Found Digital Paper with serial number 899999999999999
To discover only this specific device, call:

    /home/cuong/localdev/dpt-rp1-py/venv/bin/dptrp1 --serial 899999999999999 register

Found digital paper at 192.168.1.41
To skip the discovery process (and this message), call:

    /home/cuong/localdev/dpt-rp1-py/venv/bin/dptrp1 --addr 192.168.1.41 register

Cleaning up...
<Response [204]>
Requesting PIN...
Encoding nonce...
{"error_code":"40301","message":"Bad parameters for registration process."}
Traceback (most recent call last):
  File "/home/cuong/localdev/dpt-rp1-py/venv/bin/dptrp1", line 33, in <module>
    sys.exit(load_entry_point('dpt-rp1-py', 'console_scripts', 'dptrp1')())
  File "/home/cuong/localdev/dpt-rp1-py/dptrp1/cli/dptrp1.py", line 348, in main
    do_register(
  File "/home/cuong/localdev/dpt-rp1-py/dptrp1/cli/dptrp1.py", line 211, in do_register
    _, key, device_id = d.register()
TypeError: cannot unpack non-iterable NoneType object
`

I added a check and print error message to get the following message from the device:

`{"error_code":"40301","message":"Bad parameters for registration process."}`

**Comment by vico** [comment]
I noticed this issue looks the same as #124 so I closed it.
