### ISSUE TITLE
DEBUG:fuse.log-mixin:<- init None

### ISSUE THREAD

**Issue by hanj0415** [janten/dpt-rp1-py#137]
When I mount dpt with dptmount --config ~/.config/dpt-rp1.conf --verbose --logfile ~/.local/bin/dmlogs /mnt/data
It never return complete, and log says below at the end of line.
DEBUG:fuse.log-mixin:-> init / ()
DEBUG:fuse.log-mixin:<- init None

My environment is as below.
Ubuntu 20.04.3 LTS
dpt-rp1-py version: 0.1.16
libfuse version: libfuse2/focal,now 2.9.9-3
fusepy version: python3-fusepy/focal,focal 3.0.1-2 all

**Comment by ikuspegi** [comment]
+1 have same issue. On macOS, if you ignore this and try to take any action (copying a file etc.), the operation errors out with code -43. dptmount used to work flawlessly, I don't know what happened.

**Comment by pizzasok** [comment]
For me a similar issue is happening, but after upgrading my Quaderno to the latest firmware (1.1.00.15020FP) I get a slightly different outcome:
$ dptmount --config ~/.config/dpt-rp1.conf --verbose --logfile ~/.local/bin/dmlogs /mnt/Quaderno

Then it stalls and the log contains:

DEBUG:fuse.log-mixin:-> init / ()
DEBUG:fuse.log-mixin:<- init None
DEBUG:fuse.log-mixin:-> access / (4,)
DEBUG:fuse.log-mixin:<- access 0
DEBUG:fuse.log-mixin:-> getattr /.Trash (None,)
DEBUG:fuse.log-mixin:<- getattr '[Errno 2] No such file or directory'
DEBUG:fuse:FUSE operation getattr raised a <class 'fuse.FuseOSError'>, returning errno 2.
Traceback (most recent call last):
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 774, in getattr
    return self.fgetattr(path, buf, None)
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 1027, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 1251, in __call__
    ret = getattr(self, op)(path, *args)
  File "/home/andris/.local/lib/python3.8/site-packages/dptrp1/cli/dptmount.py", line 242, in getattr
    raise FuseOSError(ENOENT)
fuse.FuseOSError: [Errno 2] No such file or directory
DEBUG:fuse.log-mixin:-> getattr /.Trash-1000 (None,)
DEBUG:fuse.log-mixin:<- getattr '[Errno 2] No such file or directory'
DEBUG:fuse:FUSE operation getattr raised a <class 'fuse.FuseOSError'>, returning errno 2.
Traceback (most recent call last):
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 734, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 774, in getattr
    return self.fgetattr(path, buf, None)
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 1027, in fgetattr
    attrs = self.operations('getattr', self._decode_optional_path(path), fh)
  File "/home/andris/.local/lib/python3.8/site-packages/fuse.py", line 1251, in __call__
    ret = getattr(self, op)(path, *args)
  File "/home/andris/.local/lib/python3.8/site-packages/dptrp1/cli/dptmount.py", line 242, in getattr
    raise FuseOSError(ENOENT)
fuse.FuseOSError: [Errno 2] No such file or directory

**Comment by pizzasok** [comment]
Update: after a fresh install of Ubuntu 22.04.1 the problem is resolved, and dptmount works flawlessly on my Quaderno A4 2nd Gen.
