### ISSUE TITLE
Can't install/run - missing "pkg_resources"

### ISSUE THREAD

**Issue by snorlaxjones** [janten/dpt-rp1-py#149]
Issue in title, ran the install script successfully but I get this error with any attempt to run it:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\dptrp1.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\dptrp1\cli\dptrp1.py", line 12, in <module>
    from dptrp1.dptrp1 import DigitalPaper, find_auth_files, get_default_auth_files
  File "C:\Python312\Lib\site-packages\dptrp1\dptrp1.py", line 7, in <module>
    import httpsig
  File "C:\Python312\Lib\site-packages\httpsig\__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by esc430** [comment]
I am getting the same issue. Running Windows 10 on a laptop machine with Python 23.3.2 here. Any guidance would be much appreciated.

**Comment by vcyriac** [comment]
Run pip install setuptools first then try registering using dptrp1 register

**Comment by cyanescent** [comment]
Since this issue is still open, I extend it on the same topic...
It seems that this package is now deprecated, and the package `httpsig` that relies on it is abandoned.
```
~/.local/pipx/venvs/dpt-rp1-py/lib/python3.13/site-packages/httpsig/__init__.py:1: 
UserWarning: pkg_resources is deprecated as an API. 
See https://setuptools.pypa.io/en/latest/pkg_resources.html. 
The pkg_resources package is slated for removal as early as 2025-11-30. 
Refrain from using this package or pin to Setuptools<81.
```
The python package [http-message-signatures](https://github.com/pyauth/http-message-signatures) seems to be the way forward IF the device has been updated to use the new RFC 9421 standard. Otherwise pinning setuptools may be sufficient. Or fork `httpsig`.

**Comment by pournaki** [comment]
Make sure to install an older version of `setuptool`, this worked for me: 
```
pip install "setuptools<82"
```
