### ISSUE TITLE
urllib3 not found on debian but i did install python-urllib3!

### ISSUE THREAD

**Issue by samos1808** [janten/dpt-rp1-py#23]
running command : python3 setup.py  install    
get following infomations:
`Installing dptrp1 script to /usr/local/bin
Installed /usr/local/lib/python3.4/dist-packages/dpt_rp1_py-0.1.0-py3.4.egg
Processing dependencies for dpt-rp1-py==0.1.0
Searching for urllib3>=1.22
Reading https://pypi.python.org/simple/urllib3/
Download error on https://pypi.python.org/simple/urllib3/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600) -- Some packages may not be found!
Couldn't find index page for 'urllib3' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600) -- Some packages may not be found!
No local packages or download links found for urllib3>=1.22
error: Could not find suitable distribution for Requirement.parse('urllib3>=1.22')
`
i check my system did installed all urllib3 but the package name on debian is python3-urllib3 and python-urllib3 .

so  after installed dptrp1. running command dptrp1 i get:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (urllib3 1.9.1 (/usr/lib/python3/dist-packages), Requirement.parse('urllib3>=1.22'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 4, in <module>
    __import__('pkg_resources').run_script('dpt-rp1-py==0.1.0', 'dptrp1')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: urllib3>=1.22

any ideas  about this error?

**Comment by janten** [comment]
Maybe there is a separate `python3-urllib3` package? Otherwise, just install urllib using `pip3`.
