### ISSUE TITLE
Problems getting it to work

### ISSUE THREAD

**Issue by ghostwheel** [janten/dpt-rp1-py#25]
I'm on OSX 10.11.6
I managed to install, and extract client_id and key.

The command wifi-list does work.
However, other commands do not. So, for example:
```
> dptrp1 --addr 10.10.5.26 --client-id client_id.txt --key key.pem new-folder test1
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 137, in <module>
    commands[args.command](dp, *args.command_args)
  File "/usr/local/bin/dptrp1", line 36, in do_new_folder
    d.new_folder(remote_path)
  File "/usr/local/lib/python3.6/site-packages/dptrp1/dptrp1.py", line 279, in new_folder
    directory_id = directory_entry["entry_id"]
KeyError: 'entry_id'

```

Or

```
> dptrp1 --addr 10.10.5.26 --client-id client_id.txt --key key.pem upload ~/Desktop/00034.pdf "00034.pdf"
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 137, in <module>
    commands[args.command](dp, *args.command_args)
  File "/usr/local/bin/dptrp1", line 24, in do_upload
    d.upload(fh, remote_path)
  File "/usr/local/lib/python3.6/site-packages/dptrp1/dptrp1.py", line 256, in upload
    directory_id = directory_entry["entry_id"]
KeyError: 'entry_id'
```

I get the same `KeyError: 'entry_id'` error when I try other possibilities of remote path. I tried Note, Received, Received/xx.pdf, etc. 

When I try to list documents, I get the following error after a long while:
```
> dptrp1 --addr 10.10.5.26 --client-id client_id.txt --key key.pem list-documents
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 137, in <module>
    commands[args.command](dp, *args.command_args)
  File "/usr/local/bin/dptrp1", line 18, in do_list_documents
    data = d.list_documents()
  File "/usr/local/lib/python3.6/site-packages/dptrp1/dptrp1.py", line 227, in list_documents
    return data['entry_list']
KeyError: 'entry_list'
```

Is there an option to get more debugging info? Something like -v ?

Thanks!

**Comment by ghostwheel** [comment]
I think the problem is that I have too many documents, so the request times out.
When the timeout occurs, data is returned with the following keys, which does not contain 'entry_list', which is, I think why the error is returned.
```
key: error_code value: 40800
key: message valye: The request was timeout.
```

But I think the timeout does not happen from a timeout of `request.get`, because when I timeout that on purpose by giving a short `timeout=` value, the error I get is different. And giving a long timeout, `timeout=3000` does also not solve the problem.

I think it would be good if returned errors were printed.

**Comment by ghostwheel** [comment]
Here is what I added to _get_endpoint to get errors printed. Since I don't really know python, it probably is the wrong way to do things:
```
    def _get_endpoint(self, endpoint=""):
        url = "{base_url}{endpoint}" \
                .format(base_url = self.base_url,
                        endpoint = endpoint)
        req = requests.get(url, verify=False, cookies=self.cookies,timeout=3000)
        data = req.json()
        if 'error_code' in data:
            print('Error:',data['error_code'],' ',data['message'])
            print('status:',req.status_code)
        return req
```
That also showed me that the error for get-documents for code 408, timeout. I don't know if it is possible to give a RequestReadTimeout directive in the request.

I also found out that the reason new-folder failed is error 404, The designated resource was not found. The url requested was `https://10.10.5.26:8443/resolve/entry/path`.

**Comment by ghostwheel** [comment]
OK, I found the problem with 'getting it to work'. Under closed issues, I found that the remote path should be `Documents/` . Now upload and new-folder work! Great! List-documents still has the timeout problem. 

Maybe you can add a comment or examples to the main doc, saying that one should use Documents/ I guess it could even be possible to add it to the program itself as root.

**Comment by cristobaltapia** [comment]
So, I've been hitting this error with my Quaderno A4. A solution is to apply the following changes:

```diff
diff --git a/dptrp1/dptrp1.py b/dptrp1/dptrp1.py
index dfb2050..b33cf72 100755
--- a/dptrp1/dptrp1.py
+++ b/dptrp1/dptrp1.py
@@ -367,8 +367,8 @@ class DigitalPaper:
         return data['template_list']
 
     def list_documents(self):
-        data = self._get_endpoint("/documents2").json()
-        return data["entry_list"]
+        data = self.traverse_folder_recursively("Document")
+        return data
 
     def list_all(self):
         data = self._get_endpoint("/documents2?entry_type=all").json()
```

This uses the already existent method `traverse_folder_recursively(…)`. However, I don't know if this change should be done for as a default, due to performance (although I don't think it is too slow at all).

**Comment by janten** [comment]
Can you create a PR for this?

**Comment by cristobaltapia** [comment]
Sure! No problem.

**Comment by cristobaltapia** [comment]
Thanks! I guess you can close this issue now.
