### ISSUE TITLE
list-document error: KeyError: 'entry_list'

### ISSUE THREAD

**Issue by x-ji** [janten/dpt-rp1-py#36]
```
dptrp1 --client-id ~/deviceid.dat --key ~/privatekey.dat --addr 10.0.0.4 list-documents                                                                 
Traceback (most recent call last):
  File "/home/jx/.local/bin/dptrp1", line 137, in <module>
    commands[args.command](dp, *args.command_args)
  File "/home/jx/.local/bin/dptrp1", line 18, in do_list_documents
    data = d.list_documents()
  File "/home/jx/.local/lib/python3.6/site-packages/dptrp1/dptrp1.py", line 227, in list_documents
    return data['entry_list']
KeyError: 'entry_list'
```

Seems that `d.list_documents()` didn't successfully return a dictionary that contains key `entry_list` for some reason.

**Comment by ghostwheel** [comment]
I think that as in https://github.com/janten/dpt-rp1-py/issues/36 and https://github.com/janten/dpt-rp1-py/issues/25, the problem is that `_get_endpoint()` does not handle errors well. When get fails, the data returned will not have the right entries. 
If you replace `_get_endpoint()` with this:
```
    def _get_endpoint(self, endpoint=""):
        url = "{base_url}{endpoint}" \
                .format(base_url = self.base_url,
                        endpoint = endpoint)
        req = requests.get(url, verify=False, cookies=self.cookies,timeout=3000)
        data = req.json()
        if 'error_code' in data:
            print('Error:',data['error_code'],' ',data['message'])
            print('status:',req.status_code)
        return req
```
you'll be able to see the error.
Though there are probably better ways to do this.
