### ISSUE TITLE
delete do not work over USB connection

### ISSUE THREAD

**Issue by Sfinx** [janten/dpt-rp1-py#44]
```
ubuntu:~/E-Book$ dptrp1 --client-id .dpt-client --key .dpt.key --addr [fe80::60a7:46ff:fe5d:3375%enp0s20u9] list-documents
Document/Samples/Note_Sample.pdf
Document/Note/Legal Pad_20180721 (2).pdf
Document/Note/Legal Pad_20180721 (1).pdf
Document/Note/Legal Pad_20180721.pdf
Document/Samples/Basic_Operation_Guide.pdf
Document/dia.pdf
Document/Samples/Document_Sample.pdf
Document/Samples/Connectivity_Guide.pdf
rus@Yasha:~/E-Book$ dptrp1 --client-id .dpt-client --key .dpt.key --addr [fe80::60a7:46ff:fe5d:3375%enp0s20u9] delete Document/dia.pdf
Traceback (most recent call last):
  File "/usr/local/bin/dptrp1", line 142, in <module>
    commands[args.command](dp, *args.command_args)
  File "/usr/local/bin/dptrp1", line 38, in do_delete_document
    data = d.delete_document(remote_path)
  File "/usr/local/lib/python3.6/dist-packages/dptrp1/dptrp1.py", line 239, in delete_document
    remote_id = self._resolve_object_by_path(remote_path).json()['entry_id']
KeyError: 'entry_id'
ubuntu:~/E-Book$ 
```

**Comment by Sfinx** [comment]
So new-folder option just exiting without any message or new folder created

**Comment by damon-kwok** [comment]
@Sfinx what's the [fe80::60a7:46ff:fe5d:3375%enp0s20u9] ?

**Comment by Sfinx** [comment]
@damon-kwok 

You have to read the:

https://github.com/janten/dpt-rp1-py/blob/master/docs/linux-ethernet-over-usb.md

It is connected dpt-rp1
