### ISSUE TITLE
operation return 404

### ISSUE THREAD

**Issue by huddy1985** [janten/dpt-rp1-py#49]
Env: debian stretch
python: python3
DPT-RP1
the deviceid.dat and the private.dat are extract from windows
Does anyone get this error message?

./dptrp1-tools --client-id ./ws14c5c4498078433c9129970577080565/deviceid.dat --key ./ws14c5c4498078433c9129970577080565/privatekey.dat --addr digitalpaper.local delete Documents/doctor-papers/TR1846.pdf
remote path isDocuments/doctor-papers/TR1846.pdf
******************************
Documents/doctor-papers/TR1846.pdf
/resolve/entry/path/Documents/doctor-papers/TR1846.pdf
get point https://digitalpaper.local:8443/resolve/entry/path/Documents/doctor-papers/TR1846.pdf
<Response [404]>
{'Credentials': 'pZrIbn4m9KgvkKtMfJgV4Zt02M7KSAfkHegBc0QcVSJl1/0peu/qSfHs+nu0g1vt'}
<Response [404]>
get point https://digitalpaper.local:8443/resolve/entry/path/Documents/doctor-papers/TR1846.pdf
<Response [404]>
{'Credentials': 'pZrIbn4m9KgvkKtMfJgV4Zt02M7KSAfkHegBc0QcVSJl1/0peu/qSfHs+nu0g1vt'}
Traceback (most recent call last):
  File "./dptrp1-tools", line 155, in <module>
    commands[args.command](dp, *args.command_args)
  File "./dptrp1-tools", line 50, in do_delete_document
    data = d.delete_document(remote_path)
  File "/home/charlies/.local/lib/python3.5/site-packages/dptrp1/dptrp1.py", line 259, in delete_document
    remote_id = self._resolve_object_by_path(remote_path).json()['entry_id']
KeyError: 'entry_id'

**Comment by huddy1985** [comment]
The file TR1846.pdf exist definitely.
