### ISSUE TITLE
'dpt-rp1-py==0.1.6' distribution not found

### ISSUE THREAD

**Issue by Marathon2112** [janten/dpt-rp1-py#92]
I get the following error when I run `dptrp1 --help` (or any other command):
```
Traceback (most recent call last):
  File "/usr/bin/dptmount", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dpt-rp1-py==0.1.6' distribution was not found and is required by the application
```
Seems to be related to a recent python upgrade.

**Comment by Marathon2112** [comment]
Solved by reinstalling `dpt-rp1-py` using `pip3 install`.
